 version: '2'
 services:
   web:
     build:
       context: .
       dockerfile: Dockerfile.master
     ports:
      - "5000:5000"
      - "5672:5672"
     volumes:
      - .:/srv/app
     depends_on:
      - rabbitmq
   worker:
     build:
       context: .
       dockerfile: Dockerfile.worker
     volumes:
      - .:/srv/app
     depends_on:
      - rabbitmq
   rabbitmq:
     image: rabbitmq:3
   flower:
     build:
       context: .
       dockerfile: Dockerfile.worker
     command: flower --app=tasks -l info
     ports:
       - "5555:5555"
