FROM python:2.7
ENV PYTHONUNBUFFERED 1

RUN apt-get update

RUN pip install celery python-keystoneclient python-swiftclient numpy

RUN mkdir -p /srv/app/
WORKDIR /srv/app/

ADD . /srv/app/

CMD C_FORCE_ROOT=1 celery worker -A tasks
